[package]
name = "kaeru"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.18"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
chrono = "0.4"
urlencoding = "2.1" 